apiVersion: apps/v1
kind: Deployment
metadata:
  name: kittypie
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kittypie
  template:
    metadata:
      labels:
        app: kittypie
    spec:
      containers:
        - name: pieshop
          image: 
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
      imagePullSecrets:
        - name: gcr-json-key
